#+SETUPFILE: ../../../../../org-templates/level-1.org
#+TITLE: My battle with wrist pains
#+DATE: <2020-08-09 Sun 18:00>
#+OPTIONS: toc:t

#+BEGIN_QUOTE
*Note:* I'm not a doctor, dietitian or ergonomics expert. I just have spent a
lot of time to find something that works well for me. This is my experience
and you can probably take inspiration for it, but don't do stupid things and
seek expert advice if you need it.
#+END_QUOTE

In parts of the IT industry abbreviations like RSI[fn:rsi] and CTS[fn:cts]
gets thrown around fairly often. I'm guilty myself of doing this.

Approximately five years ago I thought that my career as a professional
developer was over. This was at age 25. Since then I have worked in many
ways to address these issues that I had problems with. I now feel confident
that I've beaten it for my own sake.

In this post I'm going to go through the big rough steps of what I've changed
over time. All the steps have been worked on in parallel so this blog post
isn't linear.

* Ergonomics part 1
:PROPERTIES:
:CUSTOM_ID: ergonomics-part-1
:END:

The first thing I did on this field was really when I switched to
Svorak[fn:svorak] (A Swedish Dvorak[fn:dvorak] layout) around 2006 because it
was different but also later noticed that it was more comfortable.

Then I've gone through keyboards, wrist rests, key switches, mice, and other
utilities that are supposed to be ergonomically and "fix this".

I ordered two of Keyboardio[fn:keyboardio] Model 01 from
Kickstarter[fn:keyboardio-ks] when it launched, one for home and one for
work. This set me to the path of Matias Quiet Switches[fn:matias-quiet] as a
good idea.

The delivery time was long enough so I never actually started to use it
because I jumped on a groupby for the ErgoDox Infinity[fn:ergodox-infinity]
that that was launched way later but got shipped much faster. So I got two of
that one as well to have one at work and one at home. They also happened to
support the Matias Quiet Switches[fn:matias-quiet].

I've experienced quality issues with my Matias Switches which pushed me
to move back to Cherry MX or at least something Cherry MX compatible. At a
Keyboard meetup I got the chance to try out an ErgoDox with
Zealios V2[fn:zealios]. Which I later ordered switches for and it's now my
main keyboard, together with the MX Ergo[fn:mx-ergo] that replaced my
previous M570[fn:m570].

All this costed me a lot of money on hardware, it haven't solved all problems
just magically. More has been needed.

* Good health
:PROPERTIES:
:CUSTOM_ID: good-health
:END:

Good health is the source of having a good healthy life. A lot of health
comes from working out properly and eating good food.

** Why pain?
:PROPERTIES:
:CUSTOM_ID: why-pain
:END:

At the worst point I had so much pain that I went to a doctor regarding my
issues. This was both a terrible experience but it thought me something.

The doctor told me this:
#+BEGIN_QUOTE
If you're unable to use keyboards, then maybe you should find a job where you
don't use keyboards.
#+END_QUOTE

The doctor also thought me that the source of the pain is
inflammation[fn:inflammation] that ends up in my wrists and joins and causes
the pain. To lower the immediate pain, I got pain pills.

** Handle inflammation
:PROPERTIES:
:CUSTOM_ID: handle-inflammation
:END:

The thing with inflammation is that we all have a bit of inflammation in us
all the time, from living. But it's not really a problem. Because the body
can handle inflammation on it's own as long it's small quantities. I've found
two primary ways to help the body to handle inflammation better.

*** Increased blood flow
:PROPERTIES:
:CUSTOM_ID: increased-blood-flow
:END:

Increased blood flow to the regions with inflammation will help the body
getting rid if inflammation faster.

As far as I see it, there's two reasonable ways to increase blood flow:
 - If you're numb, massage may help to let blood through.
 - Doing activities that increase blood flow, for example physical activities
   such as running, cycling, etc. Any form of workout that raises the pulse.

In the past three years I've gone from loathing physical activities to
wanting more of it and actually miss it if it's not present.

*** Ingestion of inflammation
:PROPERTIES:
:CUSTOM_ID: ingestion-of-inflammation
:END:

I started by going vegetarian several years ago as a "crazy experiment",
without really knowing anything about the benefits. During the years it's
over and over again has proved to be the right choice.

Since then, during the years I've read several books on the topic of diet.
I've learned that all animal sources of food contains
inflammation[fn:nf-inflammation]. I'm also pretty sure that adding extra
inflammation to your body when you have problems with inflammation seems to
be a bad idea.

Something that I believe have helped me greatly is to reduce the amount of
animal sources of food down to zero.

So today I aim to follow a whole-food plant based diet[fn:plant-based-diets]
that is low on fat.

Good documentaries / presentations:
 - [[https://www.imdb.com/title/tt7455754/][The Game Changers]] (IMDB link)
 - [[https://www.imdb.com/title/tt1567233/][Forks Over Knives]] (IMDB link)
 - [[https://www.youtube.com/watch?v=xnKaOL2IBPY][Michael Greger -- Food as Medicine]] (YouTube, 18:28)
 - [[https://www.youtube.com/watch?v=wxs7V0I2q1Q][Michael Klaper - Vegan Nutrition: Pure and Simple]] (YouTube, 1:35:28)

To not mention books such as:
 - [[https://nutritionfacts.org/book/][How to not Die -- Micheal Greger]]
 - [[http://www.thechinastudy.com/][The China Study -- Colin Campbell]]
 - [[https://www.amazon.com/Cheese-Trap-Breaking-Surprising-Addiction/dp/1455594687][The Cheese Trap -- Neal D Barnard]]
 - [[http://proteinaholic.com][Proteinaholic -- Garth Davis]]

* Ergonomics part 2
:PROPERTIES:
:CUSTOM_ID: ergonomics-part-2
:END:

During the spring of 2020, I went to a private doctor that did a ultrasound
scan of my wrists. The doctor scanned my wrists and said this:
#+BEGIN_QUOTE
I have good news and I have bad news:
 - I can't find anything that is broken.
 - It's probably an environmental issue of something you do in your daily
   work that causes this.
#+END_QUOTE

I've also had recorded a video of me typing on my ErgoDoxes just the week
before which I offered to show the doctor.

He was impressed by the pretty keyboard but also immediately spotted a
potential problem: How I used my wrist rests.

I did put too much pressure on my wrist rests and needed to rest my arms
more to have less pressure on the wrists. This combined with avoiding weird
angles using the wrists to hold the laptop in place and avoiding weird angles
of using my phone has made the pain manageable.

I can now feel the pain from what I do, and I can stop it by not working in
that position or doing that particular thing. I have the tools to not have
pain even after 8-10 hours of keyboard use in a single day. And I can work
a full time job without any problems.

* Summary
:PROPERTIES:
:CUSTOM_ID: summary
:END:

A TL DR of my actions that made the pain manageable:
 - Ergonomic keyboard with wrist and arm rests for long time use
 - Sticking to a fully plant based diet[fn:plant-based-diets]
 - Working out three to four times a week

It's still a daily struggle, but it's manageable and easy to live with
compared to how it was in the past.

* Footnotes
[fn:rsi]
RSI - Repetitive Strain Injury:
https://en.wikipedia.org/wiki/Repetitive_strain_injury

[fn:cts]
CTS - Carpal tunnel syndrome:
https://en.wikipedia.org/wiki/Carpal_tunnel_syndrome

[fn:svorak]
Svorak is one of the Swedish Dvoraks: http://aoeu.info

[fn:dvorak]
Dvorak keyboard layout:
https://en.wikipedia.org/wiki/Dvorak_keyboard_layout

[fn:keyboardio]
Keyboardio web shop: https://keyboard.io/

[fn:keyboardio-ks]
The Model 01: an heirloom-grade keyboard for serious typists:
https://www.kickstarter.com/projects/keyboardio/the-model-01-an-heirloom-grade-keyboard-for-seriou

[fn:matias-quiet]
Matias quiet click switches:
http://matias.ca/switches/quiet/

[fn:ergodox-infinity]
Infinity ErgoDox Mechanical Keyboard:
https://input.club/devices/infinity-ergodox/

[fn:zealios]
Purple Zealios V2 Switches (Tactile):
https://zealpc.net/products/zealio

[fn:mx-ergo]
Logitech MX Ergo trackball:
https://www.logitech.com/en-us/product/mx-ergo-wireless-trackball-mouse

[fn:m570]
Logitech M570 trackball:
https://www.logitech.com/en-us/product/wireless-trackball-m570

[fn:inflammation]
Wikipedia about inflammation:
https://en.wikipedia.org/wiki/Inflammation

[fn:nf-inflammation]
Nutrition Facts page about inflammation:
https://nutritionfacts.org/topics/inflammation/

[fn:plant-based-diets]
Nutrition Facts page about plant based diets:
https://nutritionfacts.org/topics/plant-based-diets/

#  LocalWords:  SETUPFILE CTS toc fn rsi cts Svorak svorak Keyboardio
#  LocalWords:  keyboardio Kickstarter Matias matias groupby ErgoDox
#  LocalWords:  ergodox MX Zealios ErgoDoxes Dvoraks zealios nf IMDB
#  LocalWords:  Greger Klaper Proteinaholic dvorak mx Logitech
