#+SETUPFILE: ../../../org-templates/level-1.org
#+TITLE: ~elis/drafts/health/
#+DATE: <2020-06-19 Fri 23:00>
#+OPTIONS: toc:t

* Introduction
:PROPERTIES:
:CUSTOM_ID: introduction
:END:

The purpose of this page is to be a summary of my life when it comes to
mainly physical health. It will include learning's and what I've applied.
It's partly to have as personal notes, but also that I hope to inspire
eventual readers to improve yourself. Change is always possible, but it has
to come from you.

If you feel that you want to talk to me about anything on this page, feel
free to contact me through any means described on my [[../about/#contact][/about/]] page.

* Early life / Teenage years
:PROPERTIES:
:CUSTOM_ID: early-life-teenage-years
:END:

As a child I was never really interested in physical activity, I wanted to
stay indoors top play with my computer, also I didn't care much for the gym
class in school. I went to it, I mostly did attend, that was because I had a
sense of duty to attend. The only part of gym class that I actually can say
that I remember that I enjoyed was the parts we did that contained swimming,
mostly because that I did know how to do, I'm not fast at swimming, but I'm
stable, I don't sink.

At some point during my mid-teen years I did go to a Karate class once a week
for one semester. I was dragged into that by a neighbor that wanted to go. I
dropped it to spend more time on school (but also computers really). Then I
never picked that up again, but I remember that I liked that sense of having
a group, also the uniformity of everyone dressed the same way and doing the
same things did appeal to me.

After that, during my teenage years I passed the 110kg mark on the scale,
back then I never really thought about it as a bad thing. I guess it's partly
an environmental reason with the people that you grow up with, but also what
the average people in western society is progressing towards.

So I got used to be one of the "big boys" in the room. As part of this I
started to buy all my clothes from a common line of clothes for men around
here, that had a special store where they added "XL" to the name, they only
sell clothes that is 2XL-9XL in size.

* Late Teenage years / early 20s
:PROPERTIES:
:CUSTOM_ID: late-teenage-years-early-20s
:END:

At this point I found groups of people outside of school where I finally made
some friends. Several of them are still friends up to this day. In this group
there was most often someone that was a vegetarian, when we had dinners
together, which used to happen on Wednesdays most weeks. We mostly had
vegetarian food. And it's something I picked up there as "nice to have
something different" but it was never something I "brought home" as something
that I could do for myself. Or for that matter, why would I?

Around 2011 I started to realize that those 110kg+ was probably not good in
the long run, this was around when LCHF had started to become popular, at
least it was where I was and where I picked up on it. I thought it sounded
great so I picked up on that and ran with that for a while, maybe half a year
or so before I dropped it.

* The move away from home
:PROPERTIES:
:CUSTOM_ID: the-move-away-from-home
:END:

Late 2011 had applied for a job in the other end of the country, this move
happened in a way only a young person in their 20s could do. Took a big bag
on a train and started working while finding a place to live while living on
couches. It worked out and I had a place of my own on a second hand contract
within two weeks.

Moving across the country came with both good and bad parts, the good parts
was that I grew a lot of confidence and learned to live by my own means to
take care of myself. The bad parts was that I knew nobody and didn't really
care to get to know new people.

After about 5 months I managed to get a first hand rental contract for a
bigger apartment. Quite soon after this I somehow managed to meet a person
who moved in with me that later became my wife.

During 2013 I tried to take care of my weight again, so we, together started
with LCHF, I mean, it kinda worked for me before. I managed to go from around
140kg to something around 130kg.

Then due to cultural reasons at that work place I decided that I wanted to
switch jobs and that we didn't have a reason to stay in that part of the
country. So we decided to go to Stockholm (back to Stockholm for me).

* The move back to Stockholm
:PROPERTIES:
:CUSTOM_ID: the-move-back-to-stockholm
:END:

Moving to Stockholm can be hard, this is probably true for most big cities.
Moving to another city requires two things: A steady income, A place to
live. One kinda requires the other and the other way around.

So to move to Stockholm we decided to cheat. I got a job and we moved in with
my father. Then we started looking for a place to live.

During this time when we lived with my father, we kinda went into "regular
habits" when it came to food and the amount of exercise was close to zero. I
might have chased buses to not have to wait a long time for the next bus.

When we got our own place we planned to pick up on the weight control again
and attempted to start to exercise at a local gym. During the period the
period of September 2019 to August 2016 I managed to drop from 142kg down to
135kg. Which to me was impressive at the time, yet again with LCHF. After
that we stopped because I didn't see any weight loss for the last couple of
months, so I gave up.

This is where my problems with my wrists (by using computers) started to
show up, in the beginning of December 2015 I went to the doctor about this,
the doctor, straight to my face told me the following:

#+BEGIN_QUOTE
If you're unable to use keyboards, then maybe you should find a job where you
don't use keyboards.
#+END_QUOTE

It was so bad that I had to have sick leave from work for about a week to
recover from the pain.

Around this time I started to give up on life, especially having a healthy
life, again. I didn't know what to do. Of course I knew that "exercise is
good for you". I didn't want to realize that it applies to me. I just wanted
to be happy you know.

* Switched job again, this time to TV.nu
:PROPERTIES:
:CUSTOM_ID: switched-job-again-this-time-to-tvnu
:END:

In mid April 2016 I started working at TV.nu, I joined an already
established team with great energy and a for me interesting product. Which
was exciting. I got to work on a product that people actually knew about and
actually use.

One thing that made a strong impression on me when I started was that in the
team we had one person who is a vegetarian, I looked up to him and thought
"that's a cool guy" but didn't think much more about it, until a week when
the team and I ended up at a restaurant named ~Burger & Lobsters~ that
served… Meat burgers or… Lobsters… That was the menu. I had my burger,
I was happy with it. I looked over at this guy and felt for him, there was
nothing I could do about it. But the inclusiveness of the choice of place to
eat kinda disturbed me.

During this early time at this job I also started seeing a [[https://en.wikipedia.org/wiki/Chiropractic#Philosophy][Naprapath]] in the
work building to try to resolve my issues with my wrists. She though that the
doctors statement earlier was ridiculous and that we would find another
solution to make it work for me. She managed to make things better by
massage to increase blood flow. She also managed to bring my hopes up to
convince me that there is a way to fix the issues.

** Going vegetarian
:PROPERTIES:
:CUSTOM_ID: going-vegetarian
:END:

During November 2016 me and my fiancée found a really good deal on frozen
chicken in a food-store. So we bought a box of 2kg of chicken for not much
money at all. Which felt damn good because it was a bargain.

After we was half through this box we started to get bored of it. It was
about the same every day, we decided that we wanted to "change it up" and
try something new. What we did was that we decided to eat up all the meat
in our fridge and freezer, and then go vegetarian. This limitation would
prove to be an opportunity to force ourselves out of old habits and to try
something new. Find new, better, different food to replace what we selected
to opt out from.

Doing this choice as late in the year I also got to experience how it feels
to be invited to a work dinner while being excluded because of the limited
choices of food available for you. In this case it was a Christmas buffet
where I ate potatoes, Brussels sprout and cheese. Because it was the
only three things I could find that I could eat. If it wasn't a dinner on a
moving boat I would have left in the middle of the dinner to pick up Falafel
or something…

Then during the Summer of 2017 we got married, we had a small private dinner
for family and a few friends (only people who specifically requested to
attend the ceremony). At this point I was probably the heaviest that I've
been in my entire life, way above 150kg (which is the maximum for normal
scales that are sold in regular stores, and I didn't care to find a
bigger scale).

** Starting to work out (for real this time)
:PROPERTIES:
:CUSTOM_ID: starting-to-work-out-for-real-this-time
:END:

During the spring of 2017 I gave up on all training and everything and
decided that: "I'll do it after the summer".

It may sound bad but I had a plan, the plan was that I knew that Martial
arts had worked for me in the past. So I assumed that it could work again. I
wanted to have that feeling of a group that you belong to, not going alone to
a gym over and over again.

I started looking around for something in the general area of where I lived,
and got reminded of a place nearby named [[https://sportgarden.com/][Sportgarden]] that I've seen while
I've been on walks. They had names such "Ju-Jutsu", "Goshindo", "Kickboxing"
printed on their windows. I couldn't find any good information about Goshindo
on the internet, but decided to sign up to the next semester that started
in August 2017.

#+BEGIN_QUOTE
Goshindo was founded by the owner of Sportgarden back in 1997 and is kinda
a mix of Judo, Ju-Jutsu, Boxing and some bits of wrestling. A bit like MMA
but not as much close contact. And with nice white Martial arts clothes with
differently colored belts depending on grade.
#+END_QUOTE

I started with one class a week in August 2017, then stepped it up to two
classes a week. When I started they didn't have white pants that would fit me
which made me the odd one out in a room of people dressed in white and me
with my black pants. Still above 150kg.

During this winter my wife also realized that she should stay away from milk
protein, not just lactose but the protein. It made her feel better.

For me, good cheese was a shared experience. Sure it tastes good to eat by
yourself as well. But it's even better shared. When I didn't have anyone to
share this with I kinda stopped buying fancy and good cheese, I just went for
the cheap cheese segment just to get my cheese to have on the sandwich.

I had a routine: I stepped on the scale once a week, every Monday morning
before I went to work. Then I watched the numbers going up, up, up, up from
0kg up to 149kg and then just say ~ERR~, out of operating range, today as
well. I didn't want to do this more than weekly due to seeing that ~ERR~ too
often makes you go crazy. Some days I tried to press with a single finger on
a door handle nearby, I realized that there wasn't much force needed to make
it say ~149kg~, so I knew I was getting into measurable range eventually.

After about 7 months of working out 2 times a week and eating vegetarian food
it finally changed: Early February 2018, the scale told me ~149.3kg~. This
was a big milestone. This was also a BMI of over 43.6. Not good, but I was on
track to take care of it, I was determined. And with the ability to get real
numbers I also felt the sense of control of the situation.

** Time pass by
:PROPERTIES:
:CUSTOM_ID: time-pass-by
:END:

I continue eating what I think is a good vegetarian diet with quite a lot of
cheese and dairy. Not drinking milk (I did that a lot in the past) but still
milk products on food. When I tried milk-free alternatives I thought they
were stupid and tasted bad. It was for mad or allergic people. And I was
neither. At least if you asked me back then.

My wife tried to get me to stop eating cheese. I just didn't want any of it.
I made all the classic claims that "it tastes good" and that the alternatives
"tastes horrible" and so on. I've been there. The cheese trap is real. Cheese
and milk is super addictive.

During this time I started to loose a lot of weight, but I will summarize
that in the last headline to be able to expand on this page with new updates
later on.

** Going vegan
:PROPERTIES:
:CUSTOM_ID: going-vegan
:END:

I have always looked up to vegans, I have friends who are vegans. During this
time I realize that I've done things to them that I would be upset if people
did to me today. I can only say that I apologize for my previous behavior and
hope that I can do better in the future. One example I have of this is that
before going to some friends place we went to Burger King to buy meat burgers
to eat, and we brought them with us to their place. At the time I thought it
was a perfectly fine thing to do, but now I consider it to be disrespectful
to bring such food into their homes.

During the fall of 2019 there was a new colleague starting at my job, she was
a vegan and I looked up to her as well, like all vegans. So cool. So pure of
heart and the intent to not hurt animals and things. I didn't understand the
full impact of veganism but it got me thinking more about it. My wife was
already on this train of thought.

During the fall of 2019, the documentary The Game Changers was released and
we happened to find it. We watched it. And, yeah, then every changed.

I decided to eat up my cheese and never buy cheese again. And we went vegan.

This is probably one of the best choices I've ever done. I've never felt so
good ever as I do now.

** Resolving the wrist problems
:PROPERTIES:
:CUSTOM_ID: resolving-the-wrist-problems
:END:

During this time the wrist problems got less bad, but it still came back
from time to time. Today I type on a set of ErgoDoxes which is nice but
it still could hurt. But I went to a private doctor who scanned my wrists
and said this:
#+BEGIN_QUOTE
I have good news and I have bad news:
 - I can't find anything that is broken.
 - It's probably an environmental issue of something you do in your daily
   work that causes this.
#+END_QUOTE

And a day earlier I had recorded a video of myself typing on my keyboard
so I asked him if he could have a look, and he watched the video and noticed
my cool ergonomic keyboard. But he also noted that I had my wrists hard
pressed against the wrist rest. Which caused a lot of pressure there.

So he suggested to have some kind of arm rest or using arm rests on the chair
to not have as much pressure on the wrists.

I haven't had the need to see a doctor since. All these years of pain and
suffering for that. All that time spent feeling like your professional
career as a developer is over before you turn 30 for that.

* Takeaways
:PROPERTIES:
:CUSTOM_ID: takeaways
:END:

If you are in a situation like I was, you feel that everything is hopeless,
you continue to eat to drain the sorrow. You grow bigger and so does the
sorrow. Trust me, I've seen and felt it all. It can change. But it has to
come from inside. It has to be your decision.

Before we moved back to Stockholm I used to drink extra fat milk, more or
less every day. Together with eating bacon, egg, cheese etc. I've been
through it all.

Everyone has to find their own way, this page only describes my journey. But
for pure health reasons I couldn't recommend a low fat, whole food plant
based diet enough. And I'm not alone. But I'm also not a doctor. So do your
own research, make changes and listen to the body if it feels good or not.

Go watch [[https://www.imdb.com/title/tt7455754/][The Game Changers]] on Netflix. Or just start with
[[https://www.youtube.com/watch?v=xnKaOL2IBPY][Michael Greger -- Food as Medicine]] on YouTube.

The list of resources here could be endless. But here's a few.

Good documentaries / presentations:
 - [[https://www.youtube.com/watch?v=xnKaOL2IBPY][Michael Greger - Food as Medicine]] (YouTube, 18:28)
 - [[https://www.youtube.com/watch?v=byTxzzztRBU][Ed Winters - Every Argument Against Veganism]] (YouTube, 19:30)
 - [[https://www.youtube.com/watch?v=wxs7V0I2q1Q][Michael Klaper - Vegan Nutrition: Pure and Simple]] (YouTube, 1:35:28)
 - [[https://www.youtube.com/watch?v=es6U00LMmC4][Gary Yourofsky - Best Speech You Will Ever Hear]] (YouTube, 1:10:23)
 - [[https://www.imdb.com/title/tt7455754/][The Game Changers]]
 - [[https://www.imdb.com/title/tt1567233/][Forks Over Knives]]
 - [[https://www.imdb.com/title/tt5541848/][What the health]]

To not mention books such as:
 - [[https://nutritionfacts.org/book/][How to not Die -- Micheal Greger]]
 - [[http://www.thechinastudy.com/][The China Study -- Colin Campbell]]
 - [[https://www.amazon.com/Cheese-Trap-Breaking-Surprising-Addiction/dp/1455594687][The Cheese Trap -- Neal D Barnard]]
 - [[http://proteinaholic.com][Proteinaholic -- Garth Davis]]

And many more.

Nothing tastes as good as the feeling of good health feels, and animal
sources of food prevents good health. So animal sources of food is not
worth it.

You are in control of your life. You can change your life. You just have to
decide to do it, for real. Then make a plan and stick to that plan. Make
sure it's a solid plan. Make a plan that you think that you can stick to and
live by, for the rest of your life. Don't diet according to some weird rules
for half a year to then gain it all back again. It doesn't work. You need
to find a healthy lifestyle that suits you.

* Weight progress through the years
:PROPERTIES:
:CUSTOM_ID: weight-progress-through-the-years
:END:

** Weight progress through: 2015-2016
:PROPERTIES:
:CUSTOM_ID: weight-progress-through-2015-2016
:END:

From mid September 2015 to August 2016 I managed to go from ~142.6~ to
~135.3kg~, then I bounched back to ~141.1kg~ by November 2016.

Then it just went downhill to ~>150kg~.

** Weight progress through: 2018
:PROPERTIES:
:CUSTOM_ID: weight-progress-through-2018
:END:

I finally reached ~149.3kg~ in February 2018, which made me measure daily. By
the end of the year I was down to ~124.2kg~.

That's right: That's a difference of more than ~25.1kg~ in a single year.

** Weight progress through: 2019
:PROPERTIES:
:CUSTOM_ID: weight-progress-through-2019
:END:

This trend continued during 2019.

I started the year at ~122.7kg~ and ended it at ~103.7kg~, which is a
difference of about ~19kg~ in a year.

** Weight progress through: 2020
:PROPERTIES:
:CUSTOM_ID: weight-progress-through-2020
:END:

By February 2020 I touched the ~100kg~ line which means that i dropped ~50kg~
in two years.

I started the year at ~104.4kg~ and ended it at ~84.2kg~, which is a
difference of about ~20kg~ in a year.

** Weight progress through: 2021
:PROPERTIES:
:CUSTOM_ID: weight-progress-through-2021
:END:

I started the year at ~84.0kg~.

By middle of March I've reached ~80.0kg~.

More to come here later in the year.

#  LocalWords:  SETUPFILE toc elis LCHF stockholm tvnu Naprapath BMI
#  LocalWords:  Falafel Goshindo ErgoDoxes Sportgarden Ju Jutsu MMA
#  LocalWords:  Greger Youtube Proteinaholic
