#+SETUPFILE: ../../../../../org-templates/level-1.org
#+TITLE: Why I use Free Software
#+DATE: <2021-01-16 Sat 23:30>
#+OPTIONS: toc:t

People in general may have different reasons for choosing to use Free
Software[fn:free-software], some may use it for the price, others because of
pragmatic reasons, simply put it's the best tool for the job. Others may
choose it for ethical reasons.

I didn't get into Free Software for any of the said reasons above, I got into
Free Software because it seemed different and fun. The free price point is
what made it possible for me as a teenager to play around with it as I did.

Over time it became less about fun and games to install and play with
operating systems and more about a tool, a tool that I could rely on and
learn from and use for day to day at work.

During the transition to start relying on Free Software as a tool I also
started to learn about the ethical aspects, which completely got me hooked
and is now my primary reason to keep using Free Software. These ethical
aspects have pushed me in the direction to find software that is Free
Software that match my needs, so it also happens to be, for me, simply the
best tool for the job.

Over the years I've spent quite some time on thinking about the ethical
aspects and have concluded that I find Free Software to be the only viable
choice in terms of respecting users freedom and choice to study, improve and
learn from software and how their computer works. Which makes sense since
that's the reasoning for how it was founded.

For example: I find Free Software to be one of the best ways to close, or at
least reduce the size of the digital divide[fn:digital-divide]. It may not do
it on hardware, but every bit helps.

So to conclude, in my opinion, all the reasons stated here makes Free
Software the only acceptable choice for people who care about human rights
and treating people fairly. Therefore, Free Software is humane and inclusive
software since it's mostly free of charge. This helps it to at least to
attempt to break economic barriers and income classes.

This happens to go hand in hand with the ethical aspects of
Veganism[fn:veganism]. This is sadly a connection I didn't get until many
years later. This is in a follow up post: [[../why-i-got-into-veganism][Why I got into Veganism]].

* Footnotes
[fn:digital-divide] https://en.wikipedia.org/wiki/Digital_divide
[fn:free-software] https://en.wikipedia.org/wiki/Free_software
[fn:veganism] https://en.wikipedia.org/wiki/Veganism#Ethical_veganism
