---
name: 'Squash gh-pages'

env:
  NEW_FIRST_COMMIT: HEAD~19
  DEFAULT_BRANCH: 'gh-pages'

'on':
  workflow_dispatch:
  schedule:
    - cron: '47 7 * * 2'  # At 07:47 on Tuesday.

jobs:
  squash-gh-pages-branch:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.DEFAULT_BRANCH }}
          fetch-depth: 0

      - uses: myactionway/branch-pruner-action@v2.0
        with:
          new_first_commit: ${{ env.NEW_FIRST_COMMIT }}
          branch: ${{ env.DEFAULT_BRANCH }}
