---
name: Update

'on':
  schedule:
    - cron: '0 2 * * 1,5'  # At 02:00 on Monday, and Friday.
  workflow_dispatch:

jobs:
  update:
    name: Update dependencies
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v11
      - uses: DeterminateSystems/magic-nix-cache-action@v6

      - run: 'nix flake update'
      - run: 'nix flake check'
      - run: 'nix build .#website'

      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./result

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'cron(flake): Update inputs'
